server:
  port: 9003
  servlet:
    context-path: /ddd-sample
spring:
  application:
    name: ddd-sample
  mvc:
    favicon:
      enabled: false
  messages:
    encoding: utf-8
  datasource:
    url: jdbc:mysql://xxx.xxx.xxx:3306/xxx?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF8
    hikari:
      username: 
      password: 
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 8
      minimum-idle: 2
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    password: 
    sentinel:
      master: 
      nodes: 
    database: 5
  servlet:
    multipart:
      max-file-size: 50Mb

#mybatis
mybatis-plus:
  global-config:
    db-config:
      id-type: input
      db-type: mysql
    refresh: true
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
logging:
  file: classpath:log4j2-spring.xml

jasypt:
  encryptor:
    password: 

applications:
  dddUrl: http://ddd.sf-express.com
